#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//
// Using the setMotorSyncTime command in the function moveRobot
//


void moveRobot(tMotor nMotorOne, tMotor nMotorTwo, long nTurnRatio, long nTimeMsec, long nSignedPower)
{
// setMotorSyncEncoder(nMotorOne, nMotorTwo, nTurnRatio, nEncoderCount, nSignedPower);
	// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

		// This makes it go right (all power to left)
	setMotorSyncTime( nMotorOne, nMotorTwo, 35, 1000, 75);
	sleep(1500);

	// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

			// This makes it go right (all power to left)
	setMotorSyncTime( nMotorOne, nMotorTwo, 35, 1000, 75);
	sleep(1500);

	// setMotorSyncEncoder(nMotorOne, nMotorTwo, nTurnRatio, nEncoderCount, nSignedPower);
	// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

		// This makes it go right (all power to left)
	setMotorSyncTime( nMotorOne, nMotorTwo, 35, 1000, 75);
	sleep(1500);

	// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

		// STOP
	setMotorSyncTime( nMotorOne, nMotorTwo, 0, 0, 0);
	sleep(3000);

		// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

	//Random direction
		setMotorSyncTime( nMotorOne, nMotorTwo, -50 + random(50), 1000, 75);
	sleep(1500);

			// STOP
	setMotorSyncTime( nMotorOne, nMotorTwo, 0, 0, 0);
	sleep(3000);

}


void fullspeedspin (tMotor nMotorOne, tMotor nMotorTwo, long nTurnRatio, long nTimeMsec, long nSignedPower)
{
//Forward180Back

		// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

			// This makes it go 180
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

			// This makes it go straight (both get equal amount of power)
	setMotorSyncTime( nMotorOne, nMotorTwo, nTurnRatio, nTimeMsec, nSignedPower);
	sleep(1500);

}

task main()
{
		moveRobot(leftMotor, rightMotor, 0, 1000, 75);
	 //turn ratio set to 0
	 //wait for 1 sec before moving on
	 //power set to 50 i.e. half power

		 fullspeedspin(leftMotor, rightMotor, 0, 5000, 100);
	 //turn ratio set to 0
	 //wait for 1 sec before moving on
	 //power set to 50 i.e. half power

}
