#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//
// variety of functions with different functions
//


void turn90degreesLeft(long time, long motorpower) //function for robot to turn 90 degrees to the left
{

    setMotorSpeed(leftMotor, -motorpower);  //Set the leftMotor (motor1) to half power (50)
    setMotorSpeed(rightMotor, motorpower);  //Set the rightMotor (motor6) to half power (50)
    sleep(time);  //Wait for 0.5 seconds before continuing on in the program.
}

void turn90degreesRight(long time, long motorpower) //function for robot to turn 90 degrees to the left
{

    setMotorSpeed(leftMotor, motorpower);  //Set the leftMotor (motor1) to half power (50)
    setMotorSpeed(rightMotor, -motorpower);  //Set the rightMotor (motor6) to half power (50)
    sleep(time);  //Wait for 0.5 seconds before continuing on in the program.
}

void goForward1second(long time, long motorpower) //function for robot to move forward
{

   setMotorSpeed(leftMotor, motorpower);  //Set the leftMotor (motor1) to half power (50)
   setMotorSpeed(rightMotor, motorpower);  //Set the rightMotor (motor6) to half power (50)
   sleep(time);  //Wait for 1 seconds before continuing on in the program.
}

void swingRight90degrees(long time, long motorpower) //swing the robot 90 degrees to the right
{
	// Move forward at half power for 1.5 seconds
    setMotorSpeed(leftMotor, motorpower);  //Set the leftMotor (motor1) to half power (50)
    setMotorSpeed(rightMotor, 0);  //Set the rightMotor (motor6) to half power (50)
    sleep(time);  //Wait for 1 seconds before continuing on in the program.
}

void swingLeft90degrees(long time, long motorpower) //swing the robot 90 degrees to the right
{
	  //Swing left
    setMotorSpeed(leftMotor, 0);  //Set the leftMotor (motor1) to half power (50)
    setMotorSpeed(rightMotor, motorpower );  //Set the rightMotor (motor6) to half power (50)
    sleep(time);  //Wait for 1 seconds before continuing on in the program.
}

void reverse1second(long time, long motorpower) //make the robot move backwards
{

   setMotorSpeed(leftMotor, -motorpower);  //Set the leftMotor (motor1) to half power (50)
   setMotorSpeed(rightMotor, -motorpower);  //Set the rightMotor (motor6) to half power (50)
   sleep(time);  //Wait for 1 seconds before continuing on in the program.
}

task main() //execute each of the functions above
{

   turn90degreesLeft(500,50); 
   turn90degreesRight(500,50);
   goForward1second(1000,50);
   swingRight90degrees(1000,50);
   swingLeft90degrees(1000,50);
   reverse1second(1000,50);

}
