#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

//Function to turn right
void turn90(long nMotorRatio, long dist, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, dist, power );
	sleep(1000);
	waitUntilMotorStop (rightMotor);
	waitUntilMotorStop (leftMotor);
} //turn90(40, 500, 50);

void stop1()
{
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	sleep(1000);
	setMotorSpeed(leftMotor, -50);
	setMotorSpeed(rightMotor, -50);
	sleep(500);
	setMotorSyncEncoder(leftMotor, rightMotor, -40, 500, 50);
	sleep(1000);
	waitUntilMotorStop (rightMotor);
	waitUntilMotorStop (leftMotor);
}

task main()
{
	while(SensorValue[touchSensor]==0)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	stop1();

		while(SensorValue[sonarSensor]==25)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	stop1();

	while(SensorValue[touchSensor]==0)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	stop1();

}
